### PR TITLE
type -> interface, alphabetize, remove objects which can't be instantiated

### PR DESCRIPTION
**Pull request by Validark**
- type -> interface
- alphabetize
- remove objects which can't be instantiated

### CODE REVIEW

**Comment by evaera** [comment]
I'm pretty sure uninstantiatable objects are present here to enable usage of `instanceof` with them.

**Comment by Validark** [comment]
Do they need to be newable?

**Comment by evaera** [comment]
No, don't think so.

**Comment by osyrisrblx** [comment]
Unfortunately they have to be newable or callable to work with instanceof

**Pull request closed without merging**
